transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib multicore
vmap multicore multicore
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/multicore.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_avalon_st_adapter_004.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_sdram.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_onchip.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios_cpu.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios_cpu_test_bench.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios_cpu_debug_slave_tck.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_nios_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_leds.v}
vlog -vlog01compat -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_jtag_uart_0.v}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_irq_mapper.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_avalon_st_adapter_004_error_adapter_0.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_router_006.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_router_003.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_router_002.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_router_001.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/multicore_mm_interconnect_0_router.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work multicore +incdir+/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules {/home/sebastian95/Documents/GitHub/Image-Filter-in-Heterogenuos-Processor/ProyectoQuartus/multicore/synthesis/submodules/altera_merlin_master_translator.sv}

